# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Megaton
email: martinuraka@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Main website for Megaton RAdio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://megaton.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: AmadeusNotFound

# Build settings
markdown: kramdown

livereload: true     # You no longer need to include --livereload
